### ISSUE TITLE
node red

### ISSUE THREAD

**Issue by frodo777** [avanc/photOS#118] opened 2024-02-22 17:12 UTC
can you describe a bit more what exactly has to be in the individual nodes for node red. i can't get it right.

**Comment by avanc** [comment] 2024-02-22 19:28
Did you saw the solution by @escuco in the wiki?
https://github.com/avanc/photOS/wiki/Home-Automation
Just import the flow and you should be fine (replacing `<photos-ip>`).
If not, share your flow, then I can have a look.

**Comment by frodo777** [comment] 2024-02-23 13:17
Yes, it works now. Thanks for the good project, it has been running for several years. There is still an error message in Node Red: 

23.2.2024, 14:11:30node: 95ee5064.b80798
msg : error
"MaxRedirectsError: Redirected 21 times. Aborting." 

But the monitor goes on and off.

**Comment by avanc** [comment] 2024-05-14 10:10
Closing this as duplicate of #121

**Closed as completed by avanc** 2024-05-14 10:10 UTC
