### ISSUE TITLE
Remove black border by default?

### ISSUE THREAD

**Issue by lanzer** [avanc/photOS#120] opened 2024-05-12 17:15 UTC
I noticed that by default, Raspberry Pi OS has overscan enabled, which leaves a black border around the screen.

Adding the following line in /boot/config.txt will resolve the issue:

disable_overscan=1

Perhaps this should be an option under the web config, or at least be mentioned in the Wiki.  Thanks!

**Comment by avanc** [comment] 2024-05-14 10:38
Unfortunately, I was not able to make new releases in the past and there is some backlog.

I added it into the wiki: https://github.com/avanc/photOS/wiki/FAQ#i-still-see-unnecessary-black-bars

Closing this as duplicate of #51

**Closed as completed by avanc** 2024-05-14 10:38 UTC
